[profile.default]
evm_version = "cancun"   
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/=lib/chainlink/contracts/src/v0.8/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]